name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Publish package
        run: gradle publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_ACTOR: ${{ github.actor }}
